name: tera_store
description: A new Flutter project.

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^1.0.3
  retrofit: ^3.0.1+1
  retrofit_generator: ^4.0.3+2
  build_runner: ^2.1.2
  dio: ^4.0.5
  pretty_dio_logger: ^1.1.1
  json_serializable: ^6.3.1
  analyzer: ^4.1.0
  dartz: ^0.10.1
  data_connection_checker: ^0.3.4
  shared_preferences: ^2.0.15
  get_it: ^7.2.0
  lottie: ^1.4.2
  image_picker: ^0.8.4
  carousel_slider: ^4.1.0
  easy_localization: ^3.0.0
  flutter_phoenix: ^1.0.0
  rxdart: ^0.27.5
  freezed: ^2.0.4
  internet_connection_checker: ^0.0.1+3

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.0


flutter:

  uses-material-design: true

  
  assets:
    - assets/images/


  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-Light.ttf
          weight: 300  
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600      
